---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi
    - role: nfs

- hosts: master
  become: yes
  roles:
    - role: k3s/master
    - role: metallb

- hosts: agent
  become: yes
  roles:
    - role: k3s/agent
