---
- name: Ensure NFS utilities are installed
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: true

- name: Reload systemd to recognize NFS changes
  ansible.builtin.systemd:
    daemon_reload: true

- name: Check if NFS mount point exists
  ansible.builtin.stat:
    path: "{{ mount_point }}"
  register: mount_point_stat

# - name: Copy NFS manifest to first master
#   template:
#     src: "nfs.yaml.j2"
#     dest: "/var/lib/rancher/k3s/server/manifests/nfs.yaml"
#     owner: root
#     group: root
#     mode: 0644
#   when: ansible_host == hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0])

- name: Create mount point for NFS if it doesn't exist
  ansible.builtin.file:
    path: "{{ mount_point }}"
    state: directory
    mode: '0777'
  when: mount_point is defined

- name: Mount NFS share
  ansible.posix.mount:
    path: "{{ mount_point }}"
    src: "{{ nfs_server }}:{{ nfs_share }}"
    fstype: "nfs"
    opts: "vers=4,proto=tcp,nolock"
    state: mounted
  when: mount_point is defined